language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl

branches:
  only:
    - master
    - release
    - develop

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - ./test.sh

notifications:
  slack: dwarfoftherap:K6BqeHPQ6WcvVe7gTOxq9Dlh
